---
title: "Sync-Async Analysis"
author: "Joshua M. Rosenberg & K. Bret Staudt Willet"
date: "2/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
usethis::use_git_ignore(c("*.csv", "*.rds"))
```

# Loading, setting up

```{r, include=FALSE}
library(tidyverse)
library(rtweet)
library(lubridate)
#library(devtools)  # need to install if not installed
#devtools::install_github("jrosen48/tidyttest")  # only need to run once
library(tidyttest)

#df_ss <- read_rds("snyc_async_tweets_full_metadata.rds")
df_ss <- read_csv("snyc_async_tweets_full_metadata_liwc.csv", skip = 1)

names(df_ss)[92:ncol(df_ss)] <- c("WC", "Analytic", "Clout", "Authentic", "Tone", "WPS", "Sixltr", 
"Dic", "function", "pronoun", "ppron", "i", "we", "you", "shehe", 
"they", "ipron", "article", "prep", "auxverb", "adverb", "conj", 
"negate", "verb", "adj", "compare", "interrog", "number", "quant", 
"affect", "posemo", "negemo", "anx", "anger", "sad", "social", 
"family", "friend", "female", "male", "cogproc", "insight", "cause", 
"discrep", "tentat", "certain", "differ", "percept", "see", "hear", 
"feel", "bio", "body", "health", "sexual", "ingest", "drives", 
"affiliation", "achieve", "power", "reward", "risk", "focuspast", 
"focuspresent", "focusfuture", "relativ", "motion", "space", 
"time", "work", "leisure", "home", "money", "relig", "death", 
"informal", "swear", "netspeak", "assent", "nonflu", "filler", 
"AllPunc", "Period", "Comma", "Colon", "SemiC", "QMark", "Exclam", 
"Dash", "Quote", "Apostro", "Parenth", "OtherP")

```

# RQ1: Activity

## Activity statistics and tests

```{r}
# number of sync vs. async tweets
# df_ss %>% nrow  # total number of tweets
 
sync_n <- df_ss %>% 
    pull(is_sync) %>%
    sum # add parentheses for functions

sync_n

# here is another way to write this:
df_ss %>% 
    count(is_sync)

async_n <- df_ss %>% pull(is_sync) %>% {length(.) - sync_n} # use parentheses here
async_n

# another way:
df_ss %>% janitor::tabyl(is_sync)
    
# test if difference is significant
chisq.test(c(sync_n, async_n))

df_ss %>% 
    group_by(is_sync) %>% 
    summarize(unique_tweeters =
                  {screen_name %>% tolower %>% unique %>% length} # one way may be to mutate the variable to be formatted the way you need it to before you get to the summarize
              )

chisq.test(c(8974, 1325))

df_ss %>% 
    filter(type == "ORIG") %>% 
    count(is_sync) %>% 
    group_by(is_sync) %>% 
    summarize(mean_n = mean(n))

df_ss %>% 
    filter(type == "ORIG") %>% 
    count(is_sync, screen_name) %>% 
    rename(number_of_orig_tweets = n) %>%  
    t_test(number_of_orig_tweets, is_sync)

df_ss %>% 
    count(is_sync, screen_name, type) %>% 
    complete(is_sync, screen_name, type, fill = list(n = 0)) %>% 
    filter(type == "ORIG") %>% 
    rename(number_of_orig_tweets = n) %>%  
    t_test(number_of_orig_tweets, is_sync)

df_ss %>% count(screen_name, is_sync) %>% count(screen_name) %>% count(n) 
only_one <- df_ss %>% count(screen_name, is_sync) %>% count(screen_name) %>% filter(n == 1)
both <- df_ss %>% count(screen_name, is_sync) %>% count(screen_name) %>% filter(n == 2)

df_ss %>% 
    semi_join(only_one)

chisq.test(c(8137, 488))
```

## Activity Plot: Sync vs. Async

```{r}
df_ss$date_r <- df_ss$date %>% floor_date("day")

to_plot <- df_ss %>% count(date_r, is_sync) %>% as.data.frame %>%
    tidyr::complete(date_r, is_sync, fill = list(n = 0)) %>%
    filter(date_r != ymd("2015-08-31")) %>%
    mutate(date_r = date_r %>% as_date,
           during_sync_chat = as.factor(is_sync)
           ) 
levels(to_plot$during_sync_chat) <- c('Not During a Chat (Asynchronous)',
                                      'During a Chat (Synchronous)')

ggplot(to_plot, aes(x = date_r, y = n,
                    group = during_sync_chat,
                    color = during_sync_chat)) +
    geom_point(size = 1.25) +
    geom_line(size = .7) +
    scale_color_brewer("", type = "qual", palette = 6) +
    xlab(NULL) +
    ylab("Number of Tweets") +
    scale_x_date(breaks = seq(as.Date("2015-09-01", tz = "America/Detroit"),
                              as.Date("2016-08-31", tz = "America/Detroit"),
                              by = "2 months"),
                 date_labels = "%b %g") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    theme(legend.position = "bottom")

ggsave("async-sync-time-series.png", width = 7, height = 5)
```

# All analyses - creating a table

```{r}
reply_tweets <- df_ss %>% 
    filter(type == "REPLY") %>% 
    count(reply_to_status_id) %>% 
    rename(replies_count = n)

# move to a mutate
df_ss$mentions_count <- sapply(str_split(df_ss$mentions_screen_name, " "), length) 
df_ss$hashtags_count <- sapply(str_split(df_ss$hashtags, " "), length)
df_ss$urls_count <- sapply(str_split(df_ss$urls_url, " "), length)

prepped_data <- df_ss %>% 
    filter(type == "ORIG",
           !is.na(is_sync)) %>% 
    mutate(reply_to_status_id = status_id) %>% 
    left_join(reply_tweets) %>% 
    mutate(replies_count = ifelse(is.na(replies_count), 0, replies_count)) %>% 
    select(is_sync,
           social, cogproc, posemo, negemo, work,
           favorite_count, retweet_count, replies_count, mentions_count,
           hashtags_count, urls_count) %>% 
    rename(Social = social,
           `Cognitive Processing` = cogproc,
           `Positive affect` = posemo,
           `Negative affect` = negemo,
           `Work-related Concerns` = work) %>% 
    rename(Likes = favorite_count,
           Retweets = retweet_count,
           Replies = replies_count,
           Mentions = mentions_count) %>% 
    rename(Hashtags = hashtags_count,
           URLs = urls_count)

mean_stats <- prepped_data %>% 
    group_by(is_sync) %>% 
    summarize_all(funs(mean, sd, n())) %>% 
    gather(key, val, -is_sync) %>% 
    separate(key, c("var", "stat"), sep = "\\_") %>% 
    spread(stat, val) %>% 
    mutate(se = sd / sqrt(n - 1)) %>% 
    mutate(is_sync = factor(is_sync, labels = c("Asynchronous", "Synchronous"))) %>% 
    mutate(mean_se = str_c(round(mean, 3), " (", round(se, 3), ")")) %>% 
    select(is_sync, var, mean_se) %>% 
    spread(is_sync, mean_se) %>% 
    mutate(group = c(
        "content",
        "portals",
        "interactions",
        "interactions",
        "content",
        "content",
        "interactions",
        "interactions", 
        "content", 
        "portals",
        "content"
    )) %>% 
    arrange(group, var)
```

# t-tests

```{r}
test_data <- prepped_data %>% 
    select(-is_sync) %>% 
    map(~ t.test(. ~ prepped_data$is_sync)) %>% 
    map_df(broom::tidy) %>% 
    mutate(var = names(prepped_data[, -1]))

test_data_joined <- test_data %>% 
    mutate(statistic = abs(statistic), 
           t = ifelse(p.value > .001, str_c(round(statistic, 3), " p = (", round(p.value, 3), ")"),
                      str_c(round(statistic, 3), " p < .001")),
           d = compute.es::tes(test_data$statistic, n.1 = 27361, n.2 = 8744, verbose = F)$d,
           d = abs(d)) %>% 
    select(var, t, d)
```

# Hotelling's test

```{r}
# content
prepped_data1 <- select(prepped_data, is_sync:`Work-related Concerns`)
fit1 = hotelling.test(. ~ is_sync, data = prepped_data1)
fit1

# interactions
prepped_data2 <- select(prepped_data, is_sync, Likes:Mentions)
fit2 = hotelling.test(. ~ is_sync, data = prepped_data2)
fit2

# portals
prepped_data3 <- select(prepped_data, is_sync, Hashtags, URLs)
fit3 = hotelling.test(. ~ is_sync, data = prepped_data3)
fit3
```

# Joining tables

```{r}
mean_stats %>% 
    left_join(test_data_joined, by = "var") %>% 
    select(group, var, Asynchronous, Synchronous, t, d) %>% 
    arrange(group, desc(d)) %>% 
    write_csv("combined-table.csv")
```